name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - { version: "2.13.3", binary-version: "2.13" }
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Coursier
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/coursier
            ~/.ivy2/cache
            ~/.sbt
            ~/**/node_modules
            !~/.ivy2/**/ivydata-*.properties
            !~/.ivy2/.sbt.ivy.lock
            !~/.sbt/**/*.lock
          key: ${{ runner.os }}-cache1-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/*.scala') }}-${{ hashFiles('project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-cache1-${{ matrix.scala.binary-version }}-
      - name: Run test
        run: |
          echo 'Run] sbt "; ++ ${{ matrix.scala.version }}!; set ThisBuild / scalaJSStage := FullOptStage; clean; test"'
          sbt "; ++ ${{ matrix.scala.version }}!; set ThisBuild / scalaJSStage := FullOptStage; clean; test"
